apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-master-pv
  namespace: jenkins
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  rbd:
    # 替换你自己的ceph地址
    monitors:
      - 172.30.33.39:6789
      - 172.30.33.40:6789
      - 172.30.33.41:6789
    pool: jenkins
    image: jenkins-master
    user: admin
    secretRef:
      name: jenkins-secret
    fsType: xfs
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
